version: "3.1"
services:
  php:
    build:
      context: ./
      dockerfile: php.Dockerfile
    container_name: laravel-php-80
    volumes:
      - ./:/var/www/html

  webserver:
    image: nginx:1.17.10
    container_name: laravel-nginx-webserver
    links:
      - php:fpm
    environment:
      - FPM_HOST=fpm
      - FPM_PORT=9000
    volumes:
      - ./:/var/www/html
      - ./docker/nginx_conf:/etc/nginx/conf.d/
    ports:
      - "8080:80"
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: laravel-mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: qlcv
      MYSQL_USER: qlcv
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
  node:
    build: docker/node
    container_name: node
    restart: always
    ports:
      - "3000:3000"
      - "35729:35729"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=America/Sao_Paulo
    volumes:
      - .:/var/www